services:
  db:
    container_name: postgres_db
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: maiven
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appNetwork
  api:
    container_name: nestjs-api
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - POSTGRES_HOST=postgres_db
    ports:
      - 3000:3000
    depends_on:
      - db
    restart: always
    networks:
      - appNetwork
  spa:
    container_name: vite-spa
    build:
      context: ./spa
      dockerfile: Dockerfile
    environment:
      - PORT=5173
    ports:
      - 5173:5173
    depends_on:
      - db
    networks:
      - appNetwork
volumes:
  pgdata:
networks:
  appNetwork:
